import React from "react";

/**
 * EditTreeTitle component renders a form for editing the title of a decision tree.
 * @param {Object} props - The props object containing properties passed to the component.
 * @param {string} props.title - The current title of the decision tree.
 * @param {Function} props.setTitle - Function to set the title of the decision tree.
 * @returns {JSX.Element} - Returns the JSX element for the EditTreeTitle component.
 */
const EditTreeTitle = ({ title, setTitle }) => {
  /**
   * Handles changes to the tree title input field.
   * @param {Object} event - The event object generated by the input field.
   */
  const handleTitleChange = (event) => {
    setTitle(event.target.value);
  };

  return (
    <>
      <div className="title-section">
        <div>
          {/* Tree Name */}
          <h3>Tree Name</h3>
          {/* Input field for tree name */}
          <input
            className="white-bar-input"
            type="text"
            placeholder="Enter Tree Name"
            value={title}
            onChange={handleTitleChange}
          />
        </div>
      </div>
    </>
  );
};

export default EditTreeTitle;
