import React from "react";

/**
 * AboutLink component displays an input field to enter the about article link.
 * @param {Object} props - The props object containing properties passed to the component.
 * @param {string} props.aboutLink - The current about article link.
 * @param {Function} props.setAboutLink - Function to set the about article link.
 * @returns {JSX.Element} - Returns the JSX element for the AboutLink component.
 */
const AboutLink = ({ aboutLink, setAboutLink }) => {
  /**
   * Handles changes to the about article link input field.
   * @param {Object} event - The event object generated by the input field.
   */
  const handleTextChange = (event) => {
    setAboutLink(event.target.value);
  };

  return (
    <>
      <h3>About Article Link</h3>
      <div>
        {/* Input field for about article link */}
        <input
          type="text"
          className="white-bar-input"
          placeholder="Enter About Article Link"
          onChange={handleTextChange}
          value={aboutLink}
        />
      </div>
    </>
  );
};

export default AboutLink;
